### ISSUE TITLE
Remove Baidu from ALL

### ISSUE THREAD

**Issue by v-raja** [cwerner/fastclass#12]
Baidu seems to be returning a lot of incorrect file types which cause the program to take time. Also, the -m tag works well when crawling through Google and Bing at the same time, but doesn't work so well when crawling through ALL. I suspect that it might have something to do with Baidu but I'm not sure.

So I think Baidu should be removed from the ALL option and then since the -m tag will work with the all option, we can add it to the readme.

**Comment by cwerner** [comment]
Hi.

Yeah, Beide is a bit wonky. I think your proposed changes make sense and we should remove it from the ALL option.
