### ISSUE TITLE
Download images more than 1000?

### ISSUE THREAD

**Issue by nitinnepalra** [cwerner/fastclass#21]
Hey, Thanks for the wonderful tool !! It's a great help.
I wanted to ask how to change the limit of -m which is max. limit 1000 right now.
If we want to download more than 1000 images, then what to do?

**Comment by cwerner** [comment]
Hi.

Sorry for my late response. I don't think there is a way at the moment since the 1000 images are a hard maximum from the underlying icrawler library that fastclass uses.
