### ISSUE TITLE
Feature Request: gifs

### ISSUE THREAD

**Issue by hollowgalaxy** [cwerner/fastclass#23]
Looking for a way to classify from gifs...

**Comment by cwerner** [comment]
Hm, have not tried it but gifs should be valid... Do you mean that you want to specify that you only want to download gifs?

**Comment by hollowgalaxy** [comment]
Yes

**Comment by cwerner** [comment]
Ok,

if you use the google crawler (-c GOOGLE) and add: 
`filetype:gif`
to your search string in the search definition file it only looks for gif files. The scaled images are currently converted to jpg format. If you want to retain the originals you can add the -k/ --keep flag. Only drawback is that your result folders will have "filetypegif" in their name...

Let me know if this works for you.

Cheers,
C

**Comment by hollowgalaxy** [comment]
Appreciate it. I'll try that out
