### ISSUE TITLE
fcc not finding folder

### ISSUE THREAD

**Issue by QQ-88** [cwerner/fastclass#26]
Just found this on fast.ai, great tool.
I ran a test and the download worked fine but `fcc` does not find my folder.

[Error message](https://i.imgur.com/LWhmXR1.png)
[Folder](https://i.imgur.com/lZvp5fZ.png)

Am I doing something wrong?

**Comment by cwerner** [comment]
I don't think the folder is the issue. Seems like your system lacks `tk`? 

Your error reads:
```
If this fails your Python may not be configured for Tk
```

If you are on linux try something like:
```bash
sudo apt-get install tk
```

**Comment by QQ-88** [comment]
That was indeed the issue, I assumed that would be installed by default.
Thank you for the prompt response!

**Comment by cwerner** [comment]
No Problem. I was also under the impression that `tk` is present on all mainstream distributions... 🤷‍♂
