### ISSUE TITLE
Link to your blog post in the Readme

### ISSUE THREAD

**Issue by mpoisot** [cwerner/fastclass#28]
There's a lot of great info info in your blogpost that isn't in the Readme. Why not link to it?

https://www.christianwerner.net/tech/Build-your-image-dataset-faster/

**Comment by cwerner** [comment]
Thanks for the nice words!

That's actually a good idea... I planned on refreshing my side and this repo (was all going stale since I changed positions)... but this I can do right away ;-)

**Comment by cwerner** [comment]
And done! There will be some fixes to fastclass (i.e. a Google crawler) hopefully soon, too...
