### ISSUE TITLE
Package downloading too few images

### ISSUE THREAD

**Issue by aditya3vedi** [cwerner/fastclass#32]
Thanks for this helpful tool.
I am using this and it works wonderful, the only problem I have is its just downloading 20-40 images for each class.
Am I doing something wrong or is there anyway I could make this download more images..?

I used the below command--
**fcd -c GOOGLE -s 224 C:/Users/admin/Downloads/cartypes.csv**

**Comment by cwerner** [comment]
Hi.

I haven't checked recently but some user mentioned that Google has changed it's API response to limit the number of returned images. Have you tried your query with one of the other image sources?

**Comment by aditya3vedi** [comment]
I tried with BING it still returned 100 so images for each class but that would be sufficient for my needs, thanks a lot for helping me out.

**Comment by cwerner** [comment]
Great. I’ll have to think about how to get around this google issue in the future.
