### ISSUE TITLE
SyntaxError when installing

### ISSUE THREAD

**Issue by olivermaerz** [cwerner/fastclass#4]
https://github.com/cwerner/fastclass/blob/6215d5685b7c6d7fb23e8de55c76a7862adadc42/setup.py#L22

When installing via pip gives me syntax error:

```
       version = 0.1.1,
                      ^
    SyntaxError: invalid syntax

```

**Comment by cwerner** [comment]
Hi Oliver.

This is fixed with 0.1.2
