### ISSUE TITLE
!fcc /content/tiger/Bali_tigris

### ISSUE THREAD

**Issue by ankushbanyal** [cwerner/fastclass#9]
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by cwerner** [comment]
Hi

Can you tell me a bit about your Python version/ setup? 
Are you running on a headless server?
Are you using a ssh connection (if so, try ssh -X ...).

**Comment by H4dr1en** [comment]
This bug may also occur if no graphical env is found: inside jupyter notebooks (likely regarding your "!" prepending the command) or from WSL.
